sudo: false
os: linux
dist: xenial
language: java

cache:
  directories:
  - $HOME/.gradle/caches

install:
  - sudo apt-get update
  - sudo apt-get install graphviz
  - ./test-download-omnicore-ubuntu.sh

script:
  - ./gradlew buildCI --scan --stacktrace --info
  - ./test-omni-integ-regtest.sh

jdk:
  - openjdk11
