= OmniJ Project (includes bitcoin-spock)

[WARNING]
This software is EXPERIMENTAL software for **REGTEST and TESTNET TRANSACTIONS** only. *USE ON MAINNET AT YOUR OWN RISK.*

[CAUTION]
This is pre-release software and APIs may change without notice.


== OmniJ

A Java/JVM implementation of the http://www.omnilayer.org[Omni Layer], an open-source, fully decentralized asset creation platform built on the Bitcoin blockchain.

There are currently three subprojects of OmniJ. Each of which builds a JAR artifact.

[options="header",frame="all"]
|===
| module | Description | Languages/Version

| bitcoin-rpc
| Bitcoin RPC library, command-line API/tools, integration tests
| JDK 7+ Java & Groovy

| omnij-core
| Core Omni functionality
| JDK 7+ Java-only, Android-compatible

| omnij-rpc
| Omni Core RPC library, command-line API/tools, integration tests
| JDK 7+ Java & Groovy
|===

=== OmniLayer Documentation

* https://github.com/OmniLayer/spec[Omni Protocol Specification]

=== OmniJ Documentation and Build Reports

* OmniJ https://ci.omni.foundation/job/OmniJ/javadoc/[API Doc]
* OmniJ https://ci.omni.foundation/job/OmniJ/[Unit Test Results]

=== OmniJ Maven Artifacts

Coming https://github.com/OmniLayer/OmniJ/issues/66[soon].

=== Building OmniJ

The only prerequisite for building OmniJ is having Java JDK 7 or later installed. All other prerequisites are downloaded automatically by the http://gradle.org/docs/current/userguide/gradle_wrapper.html[Gradle Wrapper] script.

. Check out this project using Git

    $ git clone https://github.com/OmniLayer/OmniJ.git

. Open a shell and set the current working directory

    cd OmniJ

. Build and test with the provided Gradle wrapper scripts. For Unix/Mac:

    ./gradlew build
+
or for Windows:

    ./gradlew.bat build

After a successful build, the jars will be in the following locations:

[options="header",frame="all"]
|===
| module | jar path

| bitcoin-rpc 
| bitcoin-rpc/build/libs/bitcoin-rpc-_version_.jar

| omnij-core
| omnij-core/build/libs/omnij-core-_version_.jar

| omnij-rpc
| omnij-rpc/build/libs/omnij-rpc-_version_.jar
|===

== Integration Testing with bitcoin-spock

[NOTE]
We've recently moved this repository from https://github.com/msgilligan/bitcoin-spock[msgilligan/bitcoin-spock] to https://github.com/OmniLayer/OmniJ[OmniLayer/OmniJ]. Since most of the issues in the Issue DB were focused on Omni RPC testing and OmniJ development, it made sense to move the whole repo. Some Bitcoin-specific portions of the repo may be extracted to another project or contributed to https://bitcoinj.github.io[bitcoinj].

Integration testing for https://bitcoin.org[Bitcoin] and http://omni.foundation[Omni Protocol] using the http://spockframework.org[Spock Framework].

There are currently three test suites contained in this project.

Bitcoin RegTest Tests::
Test Bitcoin RPC calls against an instance of `bitcoind` running in RegTest mode.

Omni RegTest Tests::
Test Bitcoin and Omni Core RPC calls against an instance of `omnicored` running in RegTest mode.

Omni Consensus Tests::
Use the `getallbalancesforid_MP` RPC to get balances for multiple Omni Protocol currencies and compare them against balance information from several well-known public Omni Protocol servers with consensus-checking Web APIs.

[NOTE]
Omni Core was formerly known as Master Core and the binary is still named `mastercored` (release version, it is still `bitcoind` on the current development branch), though that should change in a future release. The Omni Protocol was formerly Master Protocol.

== Installing pre-requisites

The only prerequisite for running these tests is an installed Java Runtime Environment. Either an Oracle or OpenJDK VM will work. Java 7 or later is required.

All other dependencies are automatically downloaded and cached by the test startup script.

== Running the tests manually

. Check out this project using Git

    $ git clone https://github.com/OmniLayer/OmniJ.git

. Start Omni Core (or bitcoind) on MainNet listening on the standard RPC port on `localhost`. The tests are configured to use the following username and password:

    rpcuser=bitcoinrpc
    rpcpassword=pass

. Open a shell and set the current working directory

    cd OmniJ

. Run the tests with the provided Gradle wrapper scripts. For Unix/Mac:

    ./gradlew :omnij-rpc:consensusTest
+
or for Windows:

    ./gradlew.bat :omnij-rpc:consensusTest
+
The above examples are for the Consensus Test, to run the other test suites replace the `:omnij-rpc:consensusTest` Gradle target with `:omnij-rpc:regTest` for the Omni RegTests or with `:bitcoin-rpc:regTest` for the Bitcoin RegTests.

== Running the tests from Jenkins

To run the test from Jenkins we are using the following (UNIX) shell scripts:

test-btc-integ-regtest.sh::
Runs BTC RPC RegTest tests against a built executable of `bitcoind` in `copied-artifacts/src` directory.

test-omni-integ-regtest.sh::
Runs Omni Core RPC regtest test against a built executable of `omnicored` in `copied-artifacts/src` directory.

test-omni-consensus-mainnet.sh::
Runs consensus tests against a built executable of `omnicored` in `copied-artifacts/src` directory.

[CAUTION]
Read the scripts carefully to make sure you understand how they work. Take special care to notice the `rm -rf` commands.

== Sample Spock Integration Tests

These sample Spock "feature tests" are from the file https://github.com/OmniLayer/OmniJ/blob/master/bitcoin-rpc/src/integ/groovy/com/msgilligan/bitcoin/rpc/BitcoinSpec.groovy#L30[BitcoinSpec.groovy].

[source,groovy]
----
    def "Use RegTest mode to generate a block upon request"() {
        given: "a certain starting height"
        def startHeight = blockCount

        when: "we generate 1 new block"
        generateBlock()

        then: "the block height is 1 higher"
        blockCount == startHeight + 1
    }

    def "When we send an amount to a newly created address, it arrives"() {
        given: "A new, empty Bitcoin address"
        def destinationAddress = getNewAddress()

        when: "we send it testAmount (from coins mined in RegTest mode)"
        sendToAddress(destinationAddress, testAmount, "comment", "comment-to")

        and: "we generate 1 new block"
        generateBlock()
 
        then: "the new address has a balance of testAmount"
        testAmount == getReceivedByAddress(destinationAddress)
    }
----

== Additional Documentation

The `adoc` (AsciiDoctor) directory of this project contains some additional documents that might be of interest:

. link:adoc/regtest-intro.adoc[Introduction to Regression Test Mode]
. link:adoc/omnij-test-design-patterns.adoc[OmniJ Test Design Patterns]
. link:adoc/omni-sto-testing.adoc[Omni Protocol Send To Owners Testing]
. link:adoc/omni-consensus-hashing.adoc[Omni Protocol Consensus Hashing Proposal]

