= OmniJ Project
Sean Gilligan <https://github.com/msgilligan>
v0.5.8
:description: OmniJ README document.
:omnij-version: 0.5.8

[WARNING]
This software is EXPERIMENTAL software for **REGTEST and TESTNET TRANSACTIONS** only. *USE ON MAINNET AT YOUR OWN RISK.*

[CAUTION]
This is pre-release software and APIs may change without notice.


== OmniJ

image:https://travis-ci.org/OmniLayer/OmniJ.svg?branch=master["Build Status", link="https://travis-ci.org/OmniLayer/OmniJ"] image:https://api.bintray.com/packages/omni/maven/omnij/images/download.svg[link="https://bintray.com/omni/maven/omnij/_latestVersion"]

A Java/JVM implementation of the http://www.omnilayer.org[Omni Layer], an open-source, fully decentralized asset creation platform built on the Bitcoin blockchain.

There are currently six subprojects of OmniJ. Each of which builds a JAR artifact.

[options="header",frame="all"]
|===
| module | Description | Languages/Version

| omnij-core
| Core Omni functionality
| JDK 8+ Java-only, Android-compatible

| omnij-dsl
| Domain Specific Language (DSL) support for Omni
| JDK 8+, Groovy language

| omnij-money
| JavaMoney support for Omni currency codes and exchanges
| JDK 8+, Java-only, tests in Groovy/Spock

| omnij-rest-client
| JavaMoney support for Omni currency codes and exchanges
| JDK 8+, Java-only, tests in Groovy/Spock

| omnij-rpc
| Omni Core RPC library, command-line API/tools, integration tests
| JDK 8+ Java & Groovy

| omnij-cli
| Builds the command-line Omni consensus-checking tool.
| JDK 8+ Java & Groovy
|===

A Bitcoin JSON-RPC client (base class), and other components used by OmniJ are in the https://github.com/ConsensusJ/consensusj[ConsensusJ] project.

=== OmniLayer Documentation

* https://github.com/OmniLayer/spec[Omni Protocol Specification]

=== OmniJ Documentation and Build Reports

* OmniJ https://ci.omni.foundation/job/OmniJ/javadoc/[API Doc]
* OmniJ https://ci.omni.foundation/job/OmniJ/[Unit Test Results]

=== OmniJ Maven Artifacts

Available on https://bintray.com/omni/maven/omnij/view[Bintray].

image::https://api.bintray.com/packages/omni/maven/omnij/images/download.svg[link="https://bintray.com/omni/maven/omnij/_latestVersion"]

WARNING: These binaries have not been audited. Use only on TestNet or RegTest.

=== Building OmniJ

The only prerequisite for building OmniJ is having Java JDK 8 or later installed. All other prerequisites are downloaded automatically by the http://gradle.org/docs/current/userguide/gradle_wrapper.html[Gradle Wrapper] script.

. Check out this project using Git

    $ git clone https://github.com/OmniLayer/OmniJ.git

. Open a shell and set the current working directory

    cd OmniJ

. Build and test with the provided Gradle wrapper scripts. For Unix/Mac:

    ./gradlew build :omnij-cli:shadowJar
+
or for Windows:

    ./gradlew.bat build :omnij-cli:shadowJar

After a successful build, the jars will be in the following locations:

[options="header",frame="all"]
|===
| module | jar path

| omnij-core
| omnij-core/build/libs/omnij-core-_version_.jar

| omnij-dsl
| omnij-dsl/build/libs/omnij-dsl-_version_.jar

| omnij-money
| omnij-dsl/build/libs/omnij-money-_version_.jar

| omnij-rest-client
| omnij-dsl/build/libs/omnij-rest-client-_version_.jar

| omnij-rpc
| omnij-rpc/build/libs/omnij-rpc-_version_.jar

| omnij-cli 
| omnij-cli/build/libs/omni-consensus-_version_.jar
|===

== Omni Integration Testing with Spock Framework

Integration testing for https://bitcoin.org[Bitcoin] and http://omni.foundation[Omni Protocol] using the http://spockframework.org[Spock Framework].

There are currently two integration test suites contained in this project.


Omni RegTest Tests::
Test Bitcoin and Omni Core RPC calls against an instance of `omnicored` running in RegTest mode.

Omni Consensus Tests::
Use the `getallbalancesforid_MP` RPC to get balances for multiple Omni Protocol currencies and compare them against balance information from several well-known public Omni Protocol servers with consensus-checking Web APIs.

=== In ConsensusJ

Bitcoin RegTest Tests::
Test Bitcoin RPC calls against an instance of `bitcoind` running in RegTest mode.

== Installing pre-requisites

The only prerequisite for running these tests is an installed Java Runtime Environment. Either an Oracle or OpenJDK VM will work. Java 8 or later is required.

All other dependencies are automatically downloaded and cached by the test startup script.

== Running the tests manually

. Check out this project using Git

    $ git clone https://github.com/OmniLayer/OmniJ.git

. Start Omni Core (or bitcoind) on MainNet listening on the standard RPC port on `localhost`. The tests are configured to use the following username and password:

    rpcuser=bitcoinrpc
    rpcpassword=pass

. Open a shell and set the current working directory

    cd OmniJ

. Run the tests with the provided Gradle wrapper scripts. For Unix/Mac:

    ./gradlew :omnij-rpc:consensusTest
+
or for Windows:

    ./gradlew.bat :omnij-rpc:consensusTest
+
The above examples are for the Consensus Test, to run the other test suites replace the `:omnij-rpc:consensusTest` Gradle target with `:omnij-rpc:regTest` for the Omni RegTests or with `:bitcoin-rpc:regTest` for the Bitcoin RegTests.

== Running the tests from Jenkins

To run the test from Jenkins we are using the following (UNIX) shell scripts:

test-omni-integ-regtest.sh::
Runs Omni Core RPC regtest test against a built executable of `omnicored` in `copied-artifacts/src` directory.

test-omni-consensus-mainnet.sh::
Runs consensus tests against a built executable of `omnicored` in `copied-artifacts/src` directory.

=== In ConsensusJ project

bitcoinj-rpcclient/run-bitcoind-regtest.sh::
Runs BTC RPC RegTest tests against a built executable of `bitcoind` in `copied-artifacts/src` directory.


[CAUTION]
Read the scripts carefully to make sure you understand how they work. Take special care to notice the `rm -rf` commands.

== Sample Spock Integration Tests

These sample Spock "feature tests" are from the file https://github.com/OmniLayer/OmniJ/blob/master/omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/ManagedPropertySpec.groovy[ManagedPropertySpec.groovy].

[source,groovy]
----
    def "A managed property can be created with transaction type 54"() {
        when:
        creationTxid = omniSendIssuanceManaged(actorAddress, Ecosystem.OMNI,
                          PropertyType.INDIVISIBLE,
                          new CurrencyID(0),
                          "Test Category", "Test Subcategory",
                          "Managed Token Name",
                          "http://www.omnilayer.org",
                          "This is a test for managed properties")
        generate()
        def creationTx = omniGetTransaction(creationTxid)
        currencyID = new CurrencyID(creationTx.propertyid as Long)

        then: "the transaction is valid"
        creationTx.valid

        and: "it has the specified values"
        creationTx.txid == creationTxid.toString()
        creationTx.type_int == 54
        creationTx.divisible == false
        creationTx.propertyname == "ManagedTokens"
        creationTx.amount as Integer == 0

        and: "there is a new property"
        omniListProperties().size() == old(omniListProperties().size()) + 1
    }

    def "A managed property has a category, subcategory, name, website and description"() {
        when:
        def propertyInfo = omniGetProperty(currencyID)

        then:
        propertyInfo.propertyid == currencyID.getValue()
        propertyInfo.divisible == false
        propertyInfo.name == "ManagedTokens"
        propertyInfo.category == "Test Category"
        propertyInfo.subcategory == "Test Subcategory"
        propertyInfo.url == "http://www.omnilayer.org"
        propertyInfo.data == "This is a test for managed properties"
    }
----

== OmniJ Command-line Consensus tool

=== Building

The OmniJ Command-line Consensus tool can be built with the following command:

    ./gradlew :omnij-cli:shadowJar

This will produce a self-contained, executable jar in `omnij-cli/build/libs/omni-consensus-`_version_`.jar`.

=== Running

To run use the following command:

    java -jar omnij-cli/build/libs/omni-consensus-0.3-SNAPSHOT.jar -?

This will output the tool's command line options.

=== Command-line Options

The tools command-line options use the https://en.bitcoin.it/wiki/Running_Bitcoin#Command-line_arguments[RPC server options] from the `bitcoin-cli` tool,  but with the following additional options:

[options="header",frame="all"]
|===
| Option | Description

| `-p` _id_
| specify an Omni property id

| `-o` _filename_
| write consensus info to _filename_

| `-omnicore-url` _url_
| specify a URL of a remote Omni Core server

| `-omnichest-url` _url_
| specify a URL of a remote Omni Chest server

| `-omniwallet-url` _url_
| specify a URL of a remote Omniwallet server

| `-compare`
| perform a consensus comparison of all properties

|===

Currently there is no way to do a consensus dump of all properties, or a comparison of a single property. To do a consensus comparison one server must be an Omni Core server specified with bitcoin-style `-rpcconnect` command-line options and the second server must be specified with the `-omnicore-url`, `-omnichest-url`, or `-omniwallet-url` options.

=== Example

To do a consensus comparison between an Omni Core server and https://www.omniwallet.org, use the following:

    java -jar omnij-cli/build/libs/omni-consensus-0.3-SNAPSHOT.jar \
        -compare -rpcssl -rpcconnect=core.host.com  \
        -rpcuser=user -rpcpassword=pass \
        -omniwallet-url=https://www.omniwallet.org


== Additional Documentation

The `doc` directory of this project contains some additional documents that might be of interest:

. link:doc/regtest-intro.adoc[Introduction to Regression Test Mode]
. link:doc/omnij-test-design-patterns.adoc[OmniJ Test Design Patterns]
. link:doc/omni-sto-testing.adoc[Omni Protocol Send To Owners Testing]
. link:doc/omni-consensus-hashing.adoc[Omni Protocol Consensus Hashing Proposal]

