= OmniJ Developer's Guide
Sean Gilligan
v0.1, July 30, 2015: Early draft
:numbered:
:toc:
:toclevels: 3
:linkattrs:
:imagesdir: images

Paragraph TBD.

== Introduction to OmniJ

This section is TBD. For now the project https://github.com/OmniLayer/OmniJ#omnij-project[README] is the best place to get started.

== JSON-RPC Clients

[plantuml, diagram-classes, svg]
....
skinparam packageStyle Rect
skinparam shadowing false
hide empty members

namespace org.consensusj.bitcoin.rpc {
    interface UntypedRPCClient
    abstract class AbstractRPCClient

    class RPCClient
    class BitcoinClient
    class BitcoinExtendedClient

    interface DynamicRpcMethodFallback << Groovy, trait >>
    class DynamicRPCClient << Groovy >>
    class BitcoinScriptingClient << Groovy >>
    class BitcoinCLIClient << Groovy >>

    UntypedRPCClient <|.. AbstractRPCClient
    AbstractRPCClient <|-- RPCClient

    UntypedRPCClient <|.. DynamicRpcMethodFallback
    RPCClient <|-- DynamicRPCClient
    DynamicRpcMethodFallback <|.. DynamicRPCClient

    RPCClient <|-- BitcoinClient
    BitcoinClient <|-- BitcoinExtendedClient
    BitcoinExtendedClient <|-- BitcoinScriptingClient
    DynamicRpcMethodFallback <|.. BitcoinScriptingClient
    BitcoinClient <|-- BitcoinCLIClient
}


namespace foundation.omni.rpc {
    class OmniClient
    class OmniScriptingClient << Groovy >>
    class OmniCLIClient << Groovy >>


    org.consensusj.bitcoin.rpc.BitcoinExtendedClient <|-- OmniClient
    OmniClient <|-- OmniScriptingClient
    org.consensusj.bitcoin.rpc.DynamicRpcMethodFallback <|.. OmniScriptingClient
    OmniClient <|-- OmniCLIClient
}


....


