= OmniJ Developer's Guide
Sean Gilligan
v0.1, July 30, 2015: Early draft
:numbered:
:toc:
:toclevels: 3
:linkattrs:
:imagesdir: images

Paragraph TBD.

== Introduction to OmniJ

This section is TBD. For now the project https://github.com/OmniLayer/OmniJ#omnij-project[README] is the best place to get started.

== JSON-RPC Clients

[plantuml, diagram-classes, svg]
....
skinparam packageStyle Rect
skinparam shadowing false
hide empty members

namespace com.msgilligan.bitcoinj.rpc {
    interface UntypedRPCClient
    abstract class AbstractRPCClient

    class RPCClient
    class BitcoinClient
    class BitcoinExtendedClient

    interface DynamicRPCFallback << Groovy, trait >>
    class DynamicRPCClient << Groovy >>
    class BitcoinScriptingClient << Groovy >>
    class BitcoinCLIClient << Groovy >>

    UntypedRPCClient <|.. AbstractRPCClient
    AbstractRPCClient <|-- RPCClient

    UntypedRPCClient <|.. DynamicRPCFallback
    RPCClient <|-- DynamicRPCClient
    DynamicRPCFallback <|.. DynamicRPCClient

    RPCClient <|-- BitcoinClient
    BitcoinClient <|-- BitcoinExtendedClient
    BitcoinExtendedClient <|-- BitcoinScriptingClient
    DynamicRPCFallback <|.. BitcoinScriptingClient
    BitcoinClient <|-- class BitcoinCLIClient
}


namespace foundation.omni.rpc {
    class OmniClient
    class OmniScriptingClient << Groovy >>
    class OmniCLIClient << Groovy >>


    com.msgilligan.bitcoinj.rpc.BitcoinExtendedClient <|-- OmniClient
    OmniClient <|-- OmniScriptingClient
    com.msgilligan.bitcoinj.rpc.DynamicRPCFallback <|.. OmniScriptingClient
    OmniClient <|-- class OmniCLIClient
}


....


